### ISSUE TITLE
Maximum execution time of 30 seconds exceeded

### ISSUE THREAD

**Issue by adityardiansyah** [jaygaha/laravel-11-frankenphp-docker#4]
How to fix this error ?
Maximum execution time of 30 seconds exceeded

**Comment by jaygaha** [comment]
@adityardiansyah 

Modify `php.ini`

If you have access to the `php.ini` file, you can change the max_execution_time directive

https://github.com/jaygaha/laravel-11-frankenphp-docker/blob/a72ca0d8ccd0935c07b4335d7348116699f4fdb2/.docker/php/php.ini#L4

**Comment by adityardiansyah** [comment]
I have setting php.ini like this 

zend.exception_ignore_args = off
expose_php = on
max_execution_time = 3600
max_input_vars = 3600
upload_max_filesize = 500M
memory_limit = 1G
post_max_size = 500M

but still the same error.

**Comment by jaygaha** [comment]
@adityardiansyah 

I think you need to recreate the docker containers again after you modified the ini file.

Stop the containers

```bash
docker compose down -v
```

Start

```bash
docker container up -d --build
```

If doesn't help with this, could you please provide me more details how you encountered this issue?

**Comment by adityardiansyah** [comment]
Still the same error.

Even though i have set php.ini and carried out command above
![image](https://github.com/user-attachments/assets/b7b7c089-0f01-4aea-ad79-1f751dc507f2)

And then response like this :
![image](https://github.com/user-attachments/assets/6e93c4be-8a4d-4c74-b231-34a7d2c6d143)

**Comment by jaygaha** [comment]
@adityardiansyah 
Is there any long running process is being executed? You need to debug that process. 🤔

**Comment by adityardiansyah** [comment]
> @adityardiansyah Is there any long running process is being executed? You need to debug that process. 🤔

I'm processing large data, that's why I installed frankenphp :D

**Comment by jaygaha** [comment]
@adityardiansyah 

You should try to use [chunk](https://laravel.com/docs/11.x/queries#chunking-results) or jobs to process these large data.

**Comment by adityardiansyah** [comment]
Okey mr @jaygaha , i will try others method. 
thanks for your response  :+1:
